# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
