# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Section', max_length=32),
        ),
    ]
