# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160324_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', max_length=124),
        ),
    ]
