# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Section'),
        ),
    ]
