# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20160325_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
